### ISSUE TITLE
Pull conventions from another project

### ISSUE THREAD

**Issue by 4erkashin** [4erkashin/todojs#2]
### TODO

- [ ] Check the reference in [my another repo](https://github.com/4erkashin/yami-locator/tree/main/.github)
- [ ] Copy the .github folder from there
- [ ] Create a PR with this changes
